backend:
  name: github
  repo: Dayong058/my-tg-webapp
  branch: main
  auth_type: implicit
  app_id: Ov23litawIu3ODaducCZ
  base_url: https://keen-khapse-f00220.netlify.app
  auth_endpoint: /admin/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "页面内容"
    folder: "content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "正文", name: "body", widget: "markdown"}
      - {label: "图片", name: "image", widget: "image"}
